apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: frauddb
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    uid: postgres-ds

